<?php
/**
 * @authors   Kanstantsin A Kamkou (2ka.by); Jeroen Herczeg
 */
$html = array();
$html[] ='<div class="navbar navbar-default">';
$html[] ='    <div class="navbar-inner">';
$html[] ='      <div class="container">';
$html[] ='        <ul class="nav navbar-nav">';
 
foreach ($this->container as $page) {
    // visibility of the page
    if (!$page->isVisible()) {
        continue;
    }
 
    // dropdown
    $dropdown = !empty($page->pages);

 
    // header
    $html[] = '<li' . ($dropdown ? ' class="dropdown"' : '') . '>';
    $html[] = '<a href="' . ($dropdown ? '# " class="dropdown-toggle" data-toggle="dropdown"' : $page->getHref()) . '">';
        

    $html[] = $page->getLabel();
 
    if ($dropdown) {
        $html[] = '<b class="caret"></b>';
    }
 
    $html[] = '</a>';
 
    if (!$dropdown) {
        $html[] = '</li>';
        continue;
    }
 
    $html[] = '<ul class="dropdown-menu">';
 
    foreach ($page->pages as $subpage) {
        // visibility of the sub-page
        if (!$subpage->isVisible()) {
            continue;
        }
        if ($subpage->getLabel() == 'divider') {
        	$html[] = '<li class="divider"></li>';
        	continue;
        }
        $html[] = '<li' . ($subpage->isActive() ? ' class="active"' : '') . '>';
        $html[] = '<a href="' . $subpage->getHref() . '">';
 
        if ($subpage->get('icon')) {
            $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
        }
 
        $html[] = $subpage->getLabel();
        $html[] = "</a>";
        $html[] = "</li>";
    }
 
    $html[] = "</ul>";
    $html[] = "</li>";
}
 
$html[] = '</ul>';
$html[] = '</div>';
$html[] = '</div>';
$html[] = '</div>';
 
echo join(PHP_EOL, $html);