<?= $this->doctype() ?>
<html>
<head>
	<meta charset="utf-8">
	<?= $this->headTitle() ?>
	<link href="\assets\bootstrap\dist\css\bootstrap.min.css" rel="stylesheet">
</head>
<body>
	<div class="container">

		<!-- Navbar -->



		<?= $this->navigation()
                 ->menu()
                 ->setPartial(array('navigation/menu.phtml', 'Core')) ?>

		<!-- breadcrumb -->
		<ol class="breadcrumb">

                <?= $this->navigation()
			             ->breadcrumbs()
			             ->setMinDepth(0)
			             ->setRenderInvisible(true)
			             ->setSeparator(' / ') ?>
			</nav>
		</ol>

		<?php echo $this->layout()->content; ?>



	</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="\assets\bootstrap\dist\js\bootstrap.min.js"></script>
</body>
</html>