<?= $this->doctype() ?>
<html>
<head>
	<meta charset="utf-8">
	<?= $this->headTitle() ?>
	<link href="assets\bootstrap\dist\css\bootstrap.min.css" rel="stylesheet">
</head>
<body>
	<div class="container">

		<!-- Navbar -->	
		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">Brand</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse">
		      <?= $this->navigation()->menu()->setUlClass('nav navbar-nav') ?>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

		<!-- breadcrumb -->
		<ol class="breadcrumb">
			    <?= $this->navigation()
			             ->breadcrumbs()
			             ->setMinDepth(0)
			             ->setRenderInvisible(true)
			             ->setSeparator(' / ') ?>
			</nav>
		</ol>

		<?php echo $this->layout()->content; ?>



	</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="assets\bootstrap\dist\js\bootstrap.min.js"></script>
</body>
</html>